"""Turn results JSON into LaTeX tables ready for the report.

Reads:
  results/<dataset>__<config>.json     (prediction metrics, from train_pykt.py)
  results/<dataset>__sequencing.json    (utility + correlation, from sequencing_eval.py)

Writes (into --out):
  table_prediction.tex
  table_sequencing.tex

These use the SAME column layout and \\label as the illustrative tables in
report/sections/06_results_discussion.tex, so you can \\input them or paste
their contents to replace the placeholders. Every number here comes from a
real run of your data -- nothing is invented.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
from typing import Dict, List


def _fmt(mean: float, std: float) -> str:
    if mean != mean:  # NaN
        return "--"
    return f"${mean:.3f} \\pm {std:.3f}$"


def load_prediction_rows(results_dir: str) -> List[Dict]:
    rows = []
    for jf in sorted(glob.glob(os.path.join(results_dir, "*.json"))):
        if jf.endswith("sequencing.json"):
            continue
        with open(jf, "r", encoding="utf-8") as f:
            res = json.load(f)
        if "aggregate" not in res:
            continue
        agg = res["aggregate"]
        rows.append(
            {
                "config": res.get("config", os.path.basename(jf)),
                "auc": agg["auc"], "rmse": agg["rmse"], "acc": agg["acc"],
            }
        )
    return rows


def write_prediction_table(rows: List[Dict], out_path: str) -> None:
    lines = [
        "% Auto-generated by make_tables.py -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\caption{Prediction accuracy (mean $\\pm$ std over 5 folds). "
        "Best AUC in bold.}",
        "\\label{tab:prediction}",
        "\\centering",
        "\\small",
        "\\begin{tabular}{@{}llll@{}}",
        "\\toprule",
        "\\textbf{Model} & \\textbf{AUC $\\uparrow$} & "
        "\\textbf{RMSE $\\downarrow$} & \\textbf{ACC $\\uparrow$} \\\\",
        "\\midrule",
    ]
    best = max((r["auc"]["mean"] for r in rows), default=float("nan"))
    for r in rows:
        auc = _fmt(r["auc"]["mean"], r["auc"]["std"])
        if r["auc"]["mean"] == best and best == best:
            auc = "\\textbf{" + auc + "}"
        rmse = _fmt(r["rmse"]["mean"], r["rmse"]["std"])
        acc = _fmt(r["acc"]["mean"], r["acc"]["std"])
        name = r["config"].replace("_", "\\_")
        lines.append(f"{name} & {auc} & {rmse} & {acc} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[make_tables] wrote {out_path}")


def write_sequencing_table(seq_path: str, out_path: str) -> None:
    if not os.path.exists(seq_path):
        print(f"[make_tables] no sequencing file at {seq_path}; skipping.")
        return
    with open(seq_path, "r", encoding="utf-8") as f:
        seq = json.load(f)
    lines = [
        "% Auto-generated by make_tables.py -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\caption{Sequencing utility $U$ (expected mastery gain) across different policies.}",
        "\\label{tab:sequencing}",
        "\\centering",
        "\\small",
        "\\begin{tabular}{@{}lllll@{}}",
        "\\toprule",
        "\\textbf{Model} & \\textbf{AUC} & "
        "\\textbf{Rand $U$} & \\textbf{Thresh $U$} & \\textbf{Greedy $U$} \\\\",
        "\\midrule",
    ]
    for r in seq.get("per_model", []):
        name = str(r["model"]).replace("_", "\\_")
        auc = r.get("auc", 0)
        u_rand = r.get("utility_random", 0)
        u_thresh = r.get("utility_mastery_threshold", 0)
        u_greedy = r.get("utility_greedy", 0)
        lines.append(f"{name} & ${auc:.3f}$ & ${u_rand:.3f}$ & ${u_thresh:.3f}$ & ${u_greedy:.3f}$ \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    corr = seq.get("correlation", {})
    for policy, c in corr.items():
        if "spearman_r" in c:
            lines.append(
                f"% {policy} correlation: Spearman rho={c['spearman_r']:.3f} "
                f"(p={c['spearman_p']:.3f}), "
                f"Pearson r={c['pearson_r']:.3f} (p={c['pearson_p']:.3f})"
            )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[make_tables] wrote {out_path}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True, help="results/ folder")
    ap.add_argument("--out", required=True, help="folder to write .tex tables")
    ap.add_argument("--sequencing", default="",
                    help="path to sequencing json (default: <results>/*sequencing.json)")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    rows = load_prediction_rows(args.results)
    if rows:
        write_prediction_table(rows, os.path.join(args.out, "table_prediction.tex"))
    else:
        print("[make_tables] no prediction results found; run train_pykt.py first.")

    seq_path = args.sequencing
    if not seq_path:
        hits = glob.glob(os.path.join(args.results, "*sequencing.json"))
        seq_path = hits[0] if hits else ""
    if seq_path:
        write_sequencing_table(seq_path, os.path.join(args.out, "table_sequencing.tex"))


if __name__ == "__main__":
    main()
